# This file is generated
# Only edit the config.ts file

cms_manual_init: true
local_backend: true
backend:
  name: git-gateway
  branch: main
media_folder: /static/uploads
public_folder: /uploads
slug:
  encoding: ascii
  clean_accents: true
collections:
  - name: Category
    label: Kategorier
    label_singular: Kategori
    folder: src/routes
    extension: mdx
    format: frontmatter
    create: true
    nested:
      depth: 100
      summary: "{{title}}"
    media_folder: "{{media_folder}}/kategorier"
    public_folder: "{{public_folder}}/kategorier"
    preview_path: /kategorier/{{slug}}
    fields:
      - label: Titel
        name: title
        widget: string
      - label: Meny
        name: meny
        widget: string
        hint: Namn på länk i menyer. Utelämna för att använda Titel.
        required: false
      - label: Beskrivning
        name: body
        widget: mdx
      - label: Bild
        name: image
        widget: image
        required: false
      - &a1
        label: Optimering av sökmotorer SEO
        name: seo
        widget: object
        collapsed: false
        fields:
          - label: Titel
            name: title
            widget: string
            required: false
            hint: Alternativ titel att visa i sökresultatet på Google. Det är en fördel om
              denna är lite mer beskrivande än title på sidan. Om denna lämnas
              tom så visas samma som Titel (på sidan).
          - label: Beskrivning
            name: description
            widget: string
            hint: Denna beskrivning visas i sökresultatet på Google. Max 160 tecken.
    meta:
      path:
        widget: string
        label: Path
        index_file: index
  - name: Author
    label: Författare
    label_singular: Författare
    folder: src/routes/foerfattare
    create: true
    slug: "{{slug}}"
    identifier_field: name
    media_folder: "{{media_folder}}/foerfattare"
    public_folder: "{{public_folder}}/foerfattare"
    fields:
      - label: Namn
        name: name
        widget: string
      - label: Publicerad
        name: published
        widget: boolean
        required: false
      - label: Porträtt
        name: image
        widget: image
        required: false
      - label: Beskrivning
        name: body
        widget: markdown
      - *a1
  - name: Book
    label: Böcker
    label_singular: Bok
    folder: src/routes/bok
    create: true
    slug: "{{slug}}"
    media_folder: "{{media_folder}}/boecker"
    public_folder: "{{public_folder}}/boecker"
    preview_path: /boecker/{{slug}}
    fields:
      - label: Titel
        name: title
        widget: string
      - label: Författare
        name: author
        widget: relation
        collection: Author
        search_fields:
          - name
        value_field: "{{slug}}"
        display_fields:
          - name
        multiple: true
      - label: Kategori
        name: kategori
        widget: relation
        collection: Category
        search_fields:
          - title
        value_field: "{{slug}}"
        display_fields:
          - title
        multiple: true
        required: false
      - label: ISBN
        name: isbn
        widget: string
        pattern:
          - "[0-9]*[-| ][0-9]*[-| ][0-9]*[-| ][0-9]*[-| ][0-9]*"
          - Must be ISBN format
      - label: Pris
        name: price
        widget: number
        value_type: int
        min: 1
        max: 999
        required: false
      - label: Publicerad
        name: published
        widget: boolean
        required: false
      - label: Utgått
        name: discontinued
        widget: boolean
        required: false
      - label: Omslag
        name: image
        widget: image
        required: false
      - label: Kort Beskrivning
        name: shortDescription
        widget: text
        required: false
      - label: Fullständig Beskrivning
        name: body
        widget: markdown
      - label: Detaljer
        hint: Information som visas i en faktaruta.
        name: generalDetails
        widget: object
        required: false
        fields:
          - label: Illustrationer
            name: illustrations
            widget: string
            required: false
          - label: Manusbearbetning
            name: manuscript
            widget: string
            required: false
          - label: Utgivningsmånad
            name: publishMonth
            widget: datetime
            format: MMM -YY
            time_format: false
            required: false
          - label: Bindning
            name: binding
            widget: select
            options:
              - Kartonnage
              - Häftad
              - Inbunden
              - Flexband
              - Danskt band
              - CD-bok
            required: false
          - label: Rekommenderad ålder
            name: age
            widget: string
            required: false
          - label: Antal sidor
            name: numPages
            widget: string
            required: false
      - label: Översatt bok
        name: translationDetails
        hint: Extra information för översatta böcker, visas i faktarutan.
        widget: object
        required: false
        fields:
          - label: Översättare
            name: translator
            widget: string
            required: false
          - label: Orginaltitel
            name: originalTitle
            widget: string
            required: false
          - label: Innehåller
            hint: "T.ex. antal cd, dvs Innehåller: 2 cd."
            name: contains
            widget: string
            required: false
      - label: Ljudbok
        name: audioDetails
        hint: Extra information för översatta böcker, visas i faktarutan.
        widget: object
        required: false
        fields:
          - label: Speltid
            name: duration
            widget: string
            required: false
          - label: Uppläsare
            name: reciter
            widget: string
            required: false
      - *a1
  - name: Pages
    label: Sidor
    label_singular: Sida
    files:
      - label: Startsida
        name: StartPage
        file: src/routes/_content/index.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Intro
            name: intro
            widget: string
          - label: Banners
            name: banners
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Bild
                name: image
                widget: image
          - label: Nyheter
            name: nyheter
            widget: list
            fields:
              - label: Bok
                name: bok
                widget: relation
                collection: Book
                search_fields:
                  - title
                display_fields:
                  - title
                value_field: "{{slug}}"
              - label: Text
                name: text
                widget: markdown
          - label: Kommande
            name: kommande
            widget: list
            fields:
              - label: Bok
                name: bok
                widget: relation
                collection: Book
                search_fields:
                  - title
                display_fields:
                  - title
                value_field: "{{slug}}"
              - label: Text
                name: text
                widget: markdown
          - label: Optimering av sökmotorer SEO
            name: seo
            widget: object
            collapsed: false
            fields:
              - label: Titel
                name: title
                widget: string
                required: false
                hint: Alternativ titel att visa i sökresultatet på Google. Det är en fördel om
                  denna är lite mer beskrivande än title på sidan. Om denna
                  lämnas tom så visas samma som Titel (på sidan).
              - label: Beskrivning
                name: description
                widget: string
                hint: Denna beskrivning visas i sökresultatet på Google. Max 160 tecken.
          - label: Layout
            name: layout
            widget: hidden
            default: startpage
